version: "3.6"
services:
  postgres_db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=medtech
      - POSTGRES_USER=fibo
      - POSTGRES_PASSWORD=fibo123
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  minio-file:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data

  # backend:
  #   image: registry.fibo.cloud/fibocloud/medtech/api
  #   restart: always
  #   environment:
  #     - database.host=postgres_db
  #     - database.port=5432
  #     - database.name=medtech
  #     - database.user=fibo
  #     - database.password=fibo123
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres_db

volumes:
  db-data:
  minio-data:
